export const ALL_CAT_OPTION = 'All';

export const CAT_BREEDS: string[] = [
  'Street',
  'Devon Rex',
  'German Rex',
  'Manx',
  'Scottish Fold',
  'Japanese Bobtail',
  'Oriental Shorthair',
  'Norwegian Forest Cat',
  'Persian',
  'European Shorthair',
  'Maine Coon',
  'Siamese',
  'Cymric',
  'Ragdoll',
  'Turkish Angora',
  'Siberian',
  'Somali',
  'Russian Blue',
  'Burmese',
  'British Shorthair',
  'Birman',
  'Abyssinian'
];

export const CAT_CITIES: string[] = [
  'Blagoevgrad',
  'Burgas',
  'Varna',
  'Veliko Tarnovo',
  'Vidin',
  'Vratsa',
  'Gabrovo',
  'Dobrich',
  'Kardzhali',
  'Kyustendil',
  'Lovech',
  'Montana',
  'Pazardzhik',
  'Pernik',
  'Pleven',
  'Plovdiv',
  'Razgrad',
  'Ruse',
  'Silistra',
  'Sliven',
  'Smolyan',
  'Sofia',
  'Stara Zagora',
  'Targovishte',
  'Haskovo',
  'Shumen',
  'Yambol'
];
